# Generated by Django 5.1.2 on 2024-10-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('first_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отечество')),
                ('speciality', models.CharField(max_length=200, verbose_name='Должность')),
                ('faculty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Институт, коллдеж')),
                ('kafedra', models.CharField(blank=True, max_length=200, null=True, verbose_name='Кафедра, цикл')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудник',
                'ordering': ['name'],
            },
        ),
    ]
