# Generated by Django 5.1.2 on 2024-10-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['post'], 'verbose_name': 'Картина', 'verbose_name_plural': 'Каритины'},
        ),
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Изображение сотрудника'),
        ),
    ]
