# Generated by Django 5.1.2 on 2024-10-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('first_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отечество')),
                ('speciality', models.CharField(max_length=200, verbose_name='Должность')),
                ('spec', models.CharField(max_length=255, verbose_name='Степень')),
                ('faculty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Институт, коллдеж')),
                ('kafedra', models.CharField(blank=True, max_length=200, null=True, verbose_name='Кафедра, цикл')),
                ('img', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Изображение сотрудника')),
                ('addres', models.CharField(max_length=255, verbose_name='Адрес')),
                ('tel', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='database_admin.post')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Каритины',
                'ordering': ['post'],
            },
        ),
    ]
